kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
        - name: echo
          image: gcr.io/google-containers/startup-script:v1
          env:
          - name: STARTUP_SCRIPT
            value: |
              #! /bin/bash
              while true; do
                echo "hello world!"
                sleep 120
              done
